const datam = {
  boxOffice: [
    {
      id: '1',
      title: '정직한 후보',
      image:
        'http://www.kobis.or.kr/common/mast/movie/2020/01/a880f5d250f04e6bacc786342972ddf4.jpg',
      rating: '3.4',
    },
    {
      id: '2',
      title: '작은 아씨들',
      image:
        'http://www.kobis.or.kr/common/mast/movie/2020/01/24088dd8a25143199a6654a6cd85dd63.jpg',
      rating: '4.4',
    },
    {
      id: '3',
      title: '클로젯',
      image:
        'http://www.kobis.or.kr/common/mast/movie/2020/01/a14b66a0cd1e492988dbecb7f563412e.jpg',
      rating: '31.4',
    },
    {
      id: '4',
      title: '기생충',
      image:
        'http://www.kobis.or.kr/common/mast/movie/2019/05/72d8601eaf93467993e92e46a45775fc.jpg',
      rating: '3',
    },
    {
      id: '5',
      title: '남산의 부장들',
      image:
        'http://www.kobis.or.kr/common/mast/movie/2019/12/6353488b52ad4f09ba799b01585340e1.jpg',
      rating: '2',
    },
    {
      id: '6',
      title: 'Ralph Lyons',
      image: 'http://placeimg.com/640/480/technics',
      rating: '1',
    },
    {
      id: '7',
      title: 'Quentin Morgan',
      image: 'http://placeimg.com/640/480/animals',
      rating: '0',
    },
    {
      id: '8',
      title: 'Dustin Gonzalez',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '2',
    },
    {
      id: '9',
      title: 'Stewart Berg',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '5',
    },
    {
      id: '10',
      title: 'Timothy Sanders',
      image: 'http://placeimg.com/640/480/sports',
      rating: '5',
    },
    {
      id: '11',
      title: 'Holmes Bender',
      image: 'http://placeimg.com/640/480/nature',
      rating: '5',
    },
    {
      id: '12',
      title: 'Caldwell Coffey',
      image: 'http://placeimg.com/640/480/food',
      rating: '5',
    },
    {
      id: '13',
      title: 'Colton Curry',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '2',
    },
    {
      id: '14',
      title: 'Avram Lara',
      image: 'http://placeimg.com/640/480/nature',
      rating: '5',
    },
    {
      id: '15',
      title: 'Craig Quinn',
      image: 'http://placeimg.com/640/480/business',
      rating: '3',
    },
    {
      id: '16',
      title: 'Brent Carroll',
      image: 'http://placeimg.com/640/480/transport',
      rating: '5',
    },
    {
      id: '17',
      title: 'Nero Knapp',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '2',
    },
    {
      id: '18',
      title: 'Odysseus Shepard',
      image: 'http://placeimg.com/640/480/technics',
      rating: '2',
    },
    {
      id: '19',
      title: 'Arden Vazquez',
      image: 'http://placeimg.com/640/480/animals',
      rating: '3',
    },
    {
      id: '20',
      title: 'Asher Buchanan',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '4',
    },
    {
      id: '21',
      title: 'Avram Hooper',
      image: 'http://placeimg.com/640/480/nature',
      rating: '2',
    },
    {
      id: '22',
      title: 'Kamal Vinson',
      image: 'http://placeimg.com/640/480/people',
      rating: '4',
    },
    {
      id: '23',
      title: 'Aquila Gates',
      image: 'http://placeimg.com/640/480/people',
      rating: '5',
    },
    {
      id: '24',
      title: 'Jonah Page',
      image: 'http://placeimg.com/640/480/food',
      rating: '2',
    },
    {
      id: '25',
      title: 'Basil Hale',
      image: 'http://placeimg.com/640/480/business',
      rating: '0',
    },
    {
      id: '26',
      title: 'Patrick Crawford',
      image: 'http://placeimg.com/640/480/technics',
      rating: '2',
    },
    {
      id: '27',
      title: 'Lee Whitaker',
      image: 'http://placeimg.com/640/480/animals',
      rating: '3',
    },
    {
      id: '28',
      title: 'Merrill Crawford',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '2',
    },
    {
      id: '29',
      title: 'Quinn Odonnell',
      image: 'http://placeimg.com/640/480/city',
      rating: '0',
    },
    {
      id: '30',
      title: 'Abdul Tucker',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '5',
    },
    {
      id: '31',
      title: 'Jelani Ramos',
      image: 'http://placeimg.com/640/480/people',
      rating: '4',
    },
    {
      id: '32',
      title: 'Ignatius Moses',
      image: 'http://placeimg.com/640/480/nature',
      rating: '1',
    },
    {
      id: '33',
      title: 'Dale Mcfarland',
      image: 'http://placeimg.com/640/480/business',
      rating: '2',
    },
    {
      id: '34',
      title: 'Cameron Alford',
      image: 'http://placeimg.com/640/480/cats',
      rating: '2',
    },
    {
      id: '35',
      title: 'Colorado Randall',
      image: 'http://placeimg.com/640/480/cats',
      rating: '3',
    },
    {
      id: '36',
      title: 'Amos Wade',
      image: 'http://placeimg.com/640/480/food',
      rating: '2',
    },
    {
      id: '37',
      title: 'Melvin Frederick',
      image: 'http://placeimg.com/640/480/cats',
      rating: '0',
    },
    {
      id: '38',
      title: 'Axel Sweeney',
      image: 'http://placeimg.com/640/480/city',
      rating: '3',
    },
    {
      id: '39',
      title: 'Laith Witt',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '1',
    },
    {
      id: '40',
      title: 'Daniel Carey',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '2',
    },
    {
      id: '41',
      title: 'Brett Vance',
      image: 'http://placeimg.com/640/480/people',
      rating: '3',
    },
    {
      id: '42',
      title: 'Carter Olsen',
      image: 'http://placeimg.com/640/480/animals',
      rating: '2',
    },
    {
      id: '43',
      title: 'Vernon Fowler',
      image: 'http://placeimg.com/640/480/city',
      rating: '3',
    },
    {
      id: '44',
      title: 'Elton Hardy',
      image: 'http://placeimg.com/640/480/transport',
      rating: '0',
    },
    {
      id: '45',
      title: 'Aristotle Ward',
      image: 'http://placeimg.com/640/480/people',
      rating: '3',
    },
    {
      id: '46',
      title: 'Abdul Murphy',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '4',
    },
    {
      id: '47',
      title: 'Ryder Anthony',
      image: 'http://placeimg.com/640/480/sports',
      rating: '2',
    },
    {
      id: '48',
      title: 'Malcolm Reeves',
      image: 'http://placeimg.com/640/480/technics',
      rating: '2',
    },
    {
      id: '49',
      title: 'Simon Whitley',
      image: 'http://placeimg.com/640/480/city',
      rating: '0',
    },
    {
      id: '50',
      title: 'Leo Miller',
      image: 'http://placeimg.com/640/480/city',
      rating: '3',
    },
    {
      id: '51',
      title: 'Hilel Nieves',
      image: 'http://placeimg.com/640/480/sports',
      rating: '0',
    },
    {
      id: '52',
      title: 'Kaseem Battle',
      image: 'http://placeimg.com/640/480/transport',
      rating: '3',
    },
    {
      id: '53',
      title: 'Neil Woodward',
      image: 'http://placeimg.com/640/480/transport',
      rating: '2',
    },
    {
      id: '54',
      title: 'Rahim Kinney',
      image: 'http://placeimg.com/640/480/business',
      rating: '4',
    },
    {
      id: '55',
      title: 'Melvin Alvarado',
      image: 'http://placeimg.com/640/480/technics',
      rating: '3',
    },
    {
      id: '56',
      title: 'Amos Stanley',
      image: 'http://placeimg.com/640/480/food',
      rating: '2',
    },
    {
      id: '57',
      title: 'Dolan Reyes',
      image: 'http://placeimg.com/640/480/transport',
      rating: '5',
    },
    {
      id: '58',
      title: 'Jack Mayer',
      image: 'http://placeimg.com/640/480/cats',
      rating: '4',
    },
    {
      id: '59',
      title: 'Knox Gilliam',
      image: 'http://placeimg.com/640/480/cats',
      rating: '2',
    },
    {
      id: '60',
      title: 'Jameson Monroe',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '0',
    },
    {
      id: '61',
      title: 'Hasad Sparks',
      image: 'http://placeimg.com/640/480/transport',
      rating: '1',
    },
    {
      id: '62',
      title: 'Zahir Dixon',
      image: 'http://placeimg.com/640/480/cats',
      rating: '0',
    },
    {
      id: '63',
      title: 'Gavin Rocha',
      image: 'http://placeimg.com/640/480/transport',
      rating: '2',
    },
    {
      id: '64',
      title: 'Ryder Bishop',
      image: 'http://placeimg.com/640/480/food',
      rating: '4',
    },
    {
      id: '65',
      title: 'Edward Chang',
      image: 'http://placeimg.com/640/480/city',
      rating: '3',
    },
    {
      id: '66',
      title: 'George Hall',
      image: 'http://placeimg.com/640/480/food',
      rating: '4',
    },
    {
      id: '67',
      title: 'Bruce Pitts',
      image: 'http://placeimg.com/640/480/abstract',
      rating: '0',
    },
    {
      id: '68',
      title: 'Jonas Hutchinson',
      image: 'http://placeimg.com/640/480/animals',
      rating: '4',
    },
    {
      id: '69',
      title: 'Preston Maynard',
      image: 'http://placeimg.com/640/480/city',
      rating: '3',
    },
    {
      id: '70',
      title: 'Otto Wheeler',
      image: 'http://placeimg.com/640/480/city',
      rating: '5',
    },
    {
      id: '71',
      title: 'Kareem Weaver',
      image: 'http://placeimg.com/640/480/technics',
      rating: '5',
    },
    {
      id: '72',
      title: 'Chaney Howard',
      image: 'http://placeimg.com/640/480/cats',
      rating: '1',
    },
    {
      id: '73',
      title: 'Keefe Perkins',
      image: 'http://placeimg.com/640/480/abstract',
      rating: '1',
    },
    {
      id: '74',
      title: 'Erich Tate',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '2',
    },
    {
      id: '75',
      title: 'Raphael Pruitt',
      image: 'http://placeimg.com/640/480/people',
      rating: '4',
    },
    {
      id: '76',
      title: 'Amery Bates',
      image: 'http://placeimg.com/640/480/food',
      rating: '1',
    },
    {
      id: '77',
      title: 'Charles Sykes',
      image: 'http://placeimg.com/640/480/technics',
      rating: '4',
    },
    {
      id: '78',
      title: 'Lionel Fuller',
      image: 'http://placeimg.com/640/480/transport',
      rating: '0',
    },
    {
      id: '79',
      title: 'Drew Santos',
      image: 'http://placeimg.com/640/480/abstract',
      rating: '5',
    },
    {
      id: '80',
      title: 'Forrest Colon',
      image: 'http://placeimg.com/640/480/fashion',
      rating: '0',
    },
    {
      id: '81',
      title: 'Hamish Zimmerman',
      image: 'http://placeimg.com/640/480/nature',
      rating: '1',
    },
    {
      id: '82',
      title: 'Channing Watson',
      image: 'http://placeimg.com/640/480/city',
      rating: '5',
    },
    {
      id: '83',
      title: 'Merritt Joyce',
      image: 'http://placeimg.com/640/480/sports',
      rating: '2',
    },
    {
      id: '84',
      title: 'Omar Murphy',
      image: 'http://placeimg.com/640/480/transport',
      rating: '4',
    },
    {
      id: '85',
      title: 'Dieter Barnett',
      image: 'http://placeimg.com/640/480/nature',
      rating: '2',
    },
    {
      id: '86',
      title: 'Logan Rodriguez',
      image: 'http://placeimg.com/640/480/nature',
      rating: '0',
    },
    {
      id: '87',
      title: 'Xanthus Torres',
      image: 'http://placeimg.com/640/480/people',
      rating: '2',
    },
    {
      id: '88',
      title: 'Levi Beasley',
      image: 'http://placeimg.com/640/480/transport',
      rating: '1',
    },
    {
      id: '89',
      title: 'Alan Briggs',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '0',
    },
    {
      id: '90',
      title: 'Zachery Lowe',
      image: 'http://placeimg.com/640/480/city',
      rating: '1',
    },
    {
      id: '91',
      title: 'Arthur Cotton',
      image: 'http://placeimg.com/640/480/animals',
      rating: '1',
    },
    {
      id: '92',
      title: 'Tarik Shelton',
      image: 'http://placeimg.com/640/480/abstract',
      rating: '2',
    },
    {
      id: '93',
      title: 'Timon Tyson',
      image: 'http://placeimg.com/640/480/cats',
      rating: '1',
    },
    {
      id: '94',
      title: 'Moses Schwartz',
      image: 'http://placeimg.com/640/480/sports',
      rating: '1',
    },
    {
      id: '95',
      title: 'Demetrius Perkins',
      image: 'http://placeimg.com/640/480/nature',
      rating: '1',
    },
    {
      id: '96',
      title: 'Reese Sweeney',
      image: 'http://placeimg.com/640/480/transport',
      rating: '1',
    },
    {
      id: '97',
      title: 'Malcolm Gray',
      image: 'http://placeimg.com/640/480/cats',
      rating: '1',
    },
    {
      id: '98',
      title: 'Curran Frost',
      image: 'http://placeimg.com/640/480/transport',
      rating: '5',
    },
    {
      id: '99',
      title: 'Brennan Harrison',
      image: 'http://placeimg.com/640/480/people',
      rating: '1',
    },
    {
      id: '100',
      title: 'Deacon Vega',
      image: 'http://placeimg.com/640/480/technics',
      rating: '4',
    },
    {
      id: '101',
      title: 'Quentin Anthony',
      image: 'http://placeimg.com/640/480/city',
      rating: '5',
    },
    {
      id: '102',
      title: 'Harper Dean',
      image: 'http://placeimg.com/640/480/nature',
      rating: '2',
    },
    {
      id: '103',
      title: 'Nissim Graham',
      image: 'http://placeimg.com/640/480/business',
      rating: '1',
    },
    {
      id: '104',
      title: 'Timon Whitehead',
      image: 'http://placeimg.com/640/480/nightlife',
      rating: '3',
    },
    {
      id: '105',
      title: 'Kevin Morrison',
      image: 'http://placeimg.com/640/480/business',
      rating: '1',
    },
  ],
};

export default datam;
